import { runAi } from "../../src/lib/operations/ai";
import { saveReservation } from "../../src/lib/operations/reservations";
import test from 'node:test';
import assert from 'node:assert/strict';
import prisma from '../../src/lib/prisma';
import {mutate} from '../../src/lib/operations/core';
import {clock,correctClock} from '../../src/lib/operations/timeclock';
import {queueNotification,processNextNotification,recordDeliveryEvidence} from '../../src/lib/operations/notifications';
const enabled=process.env.RUN_OPERATIONS_TESTS==='1';
const request=(key:string)=>new Request('http://localhost/test',{method:'POST',headers:{'Idempotency-Key':key}});
test('durable mutations, time ownership, provider evidence and uncertain delivery recovery',{skip:!enabled},async()=>{
 const user=await prisma.user.create({data:{email:`test-${Date.now()}@example.test`,password:'not-a-login',role:'ADMIN'}});const actor={userId:user.id,role:'ADMIN'};
 const staff=await prisma.staff.create({data:{userId:user.id,firstName:'Test',lastName:'Worker',position:'Test',hourlyRate:20}});
 const input={staffId:staff.id,action:'clockIn' as const};const req=request(`clock-${user.id}`);
 const [first,second]=await Promise.all([mutate(actor,req,'clock',input,tx=>clock(tx,actor,input)),mutate(actor,req,'clock',input,tx=>clock(tx,actor,input))]);assert.equal(first.id,second.id);assert.equal(await prisma.timeClock.count({where:{staffId:staff.id}}),1);
 await assert.rejects(mutate(actor,req,'clock',{...input,action:'clockOut'},()=>Promise.resolve(null)),/different changes/);
 await assert.rejects(prisma.$transaction(tx=>clock(tx,{userId:'outsider',role:'STAFF'},{staffId:staff.id,action:'clockOut'})),/own time/);
 await assert.rejects(prisma.$transaction(tx=>correctClock(tx,actor,{id:first.id,version:first.version,action:'approve',reason:'Test review'})),/Close the shift/);
 process.env.RESEND_API_KEY='test-fixture';process.env.RESEND_FROM_EMAIL='fixture@example.test';process.env.ENABLE_NOTIFICATION_DELIVERY='true';
 const msg={type:'CUSTOM' as const,channel:'EMAIL' as const,recipient:'recipient@example.test',subject:'Test',message:'Fixture, never sent',consentConfirmed:true as const};
 const queued=await queueNotification(actor,request(`message-${user.id}`),msg);
 let calls=0;const fake=(async()=>{calls++;return Response.json({id:`provider-${queued.id}`});}) as typeof fetch;
 await Promise.all([processNextNotification(fake),processNextNotification(fake)]);assert.equal(calls,1);
 assert.equal((await prisma.notification.findUniqueOrThrow({where:{id:queued.id}})).status,'SENT');
 const evidence={provider:'resend',reference:`provider-${queued.id}`,status:'DELIVERED' as const,eventId:'fixture-event'};await recordDeliveryEvidence(evidence);await recordDeliveryEvidence(evidence);
 assert.equal((await prisma.notification.findUniqueOrThrow({where:{id:queued.id}})).status,'DELIVERED');
 const uncertain=await queueNotification(actor,request(`uncertain-${user.id}`),msg);
 await processNextNotification((async()=>{throw new Error('timeout fixture');}) as typeof fetch);
 assert.equal((await prisma.notification.findUniqueOrThrow({where:{id:uncertain.id}})).status,'UNKNOWN');
 await processNextNotification(fake);assert.equal(calls,1);
 const table=await prisma.table.create({data:{number:999,capacity:4,section:'Fixture'}});
 const time=new Date(Date.now()+86400000).toISOString();const booking={customerName:'Fixture guest',customerPhone:'+12025550123',partySize:2,time,tableId:table.id};
 const reserved=await mutate(actor,request(`booking-${user.id}`),'booking',booking,tx=>saveReservation(tx,actor,booking));
 await assert.rejects(mutate(actor,request(`conflict-${user.id}`),'booking',booking,tx=>saveReservation(tx,actor,booking)),/already reserved/);
 assert.equal(await prisma.reservation.count({where:{tableId:table.id}}),1);
 await assert.rejects(mutate(actor,request(`stale-${user.id}`),'booking',{},tx=>saveReservation(tx,actor,{version:reserved.version+1,status:'CONFIRMED'},reserved.id)),/changed/);
 process.env.OPENROUTER_API_KEY='fixture-only';process.env.OPENROUTER_MODEL='fixture-model';
 let aiCalls=0;
 const aiFake=(async()=>{aiCalls++;return Response.json({id:'fixture-ai-receipt',model:'fixture-model',usage:{cost:0.001,total_tokens:20},choices:[{finish_reason:'stop',message:{content:JSON.stringify({title:'Fixture draft',summary:'No actions executed',suggestions:[],limitations:['Synthetic provider test']})}}]});}) as typeof fetch;
 const aiRequest=request(`ai-${user.id}`);const aiInput={feature:'daily-summary' as const,instructions:'Summarize test records'};
 const aiRun=await runAi(actor,aiRequest,aiInput,aiFake);assert.equal(aiRun.status,'DRAFT');assert.equal(aiRun.providerRef,'fixture-ai-receipt');assert.equal(Number(aiRun.costUsd),0.001);
 await runAi(actor,aiRequest,aiInput,aiFake);assert.equal(aiCalls,1);
 await prisma.$disconnect();
});
